version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Build step: No build needed for this app"
  post_build:
    commands:
      - echo "Zipping files for deployment"
      - zip -r ooo.zip .
artifacts:
  files:
    - ooo.zip
