version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "No build process for basic Node.js app"
artifacts:
  files:
    - "**/*"
